server:
  port: 9191

spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/MiniProject
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true

